"""add job id to tasks

Revision ID: 01ae3ff4315c
Revises: b38a1f5b4d61
Create Date: 2026-03-14 09:22:55.760922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ae3ff4315c'
down_revision: Union[str, Sequence[str], None] = 'b38a1f5b4d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('job_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'job_id')
    # ### end Alembic commands ###
