"""Add additional prompt

Revision ID: 0fa2b311f73c
Revises: a631e35f59aa
Create Date: 2026-04-20 06:15:18.486078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa2b311f73c'
down_revision: Union[str, Sequence[str], None] = 'a631e35f59aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('additional_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'additional_prompt')
    # ### end Alembic commands ###
