"""Make url nullable

Revision ID: 9e1ed8adb9cf
Revises: 01ae3ff4315c
Create Date: 2026-03-15 06:09:58.609803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1ed8adb9cf'
down_revision: Union[str, Sequence[str], None] = '01ae3ff4315c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clips', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clips', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
