"""Add cut-markers

Revision ID: a631e35f59aa
Revises: 9e1ed8adb9cf
Create Date: 2026-04-11 09:10:45.850230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a631e35f59aa'
down_revision: Union[str, Sequence[str], None] = '9e1ed8adb9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('cut_markers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'cut_markers')
    # ### end Alembic commands ###
