"""use clip type based on json from pipeline

Revision ID: b38a1f5b4d61
Revises: 2836f85f72c1
Create Date: 2026-03-11 12:22:39.650981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38a1f5b4d61'
down_revision: Union[str, Sequence[str], None] = '2836f85f72c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('clip_index', sa.Integer(), nullable=False))
    op.add_column('clips', sa.Column('start_seconds', sa.Float(), nullable=False))
    op.add_column('clips', sa.Column('end_seconds', sa.Float(), nullable=False))
    op.add_column('clips', sa.Column('duration_seconds', sa.Float(), nullable=False))
    op.add_column('clips', sa.Column('script_description', sa.Text(), nullable=False))
    op.add_column('clips', sa.Column('aesthetics', sa.Text(), nullable=False))
    op.add_column('clips', sa.Column('camera_movement', sa.Text(), nullable=False))
    op.drop_column('clips', 'start_offset_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('start_offset_ms', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('clips', 'camera_movement')
    op.drop_column('clips', 'aesthetics')
    op.drop_column('clips', 'script_description')
    op.drop_column('clips', 'duration_seconds')
    op.drop_column('clips', 'end_seconds')
    op.drop_column('clips', 'start_seconds')
    op.drop_column('clips', 'clip_index')
    # ### end Alembic commands ###
