"""Add non-nullable name

Revision ID: d4aa3c9713be
Revises: 0fa2b311f73c
Create Date: 2026-04-22 11:10:01.798940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4aa3c9713be'
down_revision: Union[str, Sequence[str], None] = '0fa2b311f73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('tasks', sa.Column('name', sa.Text(), nullable=True))

    op.execute("UPDATE tasks SET name = 'Untitled project' WHERE name IS NULL")

    op.alter_column('tasks', 'name', existing_type=sa.Text(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###
